"""보조금 샘플 데이터 — 나이는 만 나이 기준"""

SUBSIDIES = [
    {
        "id": 1,
        "name": "청년창업지원금",
        "category": "창업",
        "description": "만 39세 이하 청년의 창업 활동을 지원하는 보조금",
        "amount": "최대 5,000만원",
        "min_age": 19,
        "max_age": 39,
        "gender": "무관",
        "regions": ["서울", "경기", "인천", "부산", "대구", "광주", "대전", "울산", "세종"],
        "max_income_percentile": 100,
        "business_types": ["제조업", "IT", "서비스업", "도소매업"],
        "required_docs": ["사업계획서", "신분증", "소득증명서"],
        "deadline": "2026-06-30",
        "org": "중소벤처기업부",
    },
    {
        "id": 2,
        "name": "경력단절여성 재취업 지원금",
        "category": "취업",
        "description": "경력단절 여성의 재취업 및 직업훈련을 지원",
        "amount": "최대 300만원",
        "min_age": 25,
        "max_age": 55,
        "gender": "여성",
        "regions": ["서울", "경기", "인천", "부산", "대구", "광주", "대전"],
        "max_income_percentile": 80,
        "business_types": [],
        "required_docs": ["경력단절확인서", "신분증", "가족관계증명서"],
        "deadline": "2026-05-31",
        "org": "여성가족부",
    },
    {
        "id": 3,
        "name": "농업인 시설현대화 보조금",
        "category": "농업",
        "description": "농업 시설 현대화 및 스마트팜 전환을 위한 지원금",
        "amount": "최대 3억원 (자부담 30%)",
        "min_age": 18,
        "max_age": 70,
        "gender": "무관",
        "regions": ["경기", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"],
        "max_income_percentile": 100,
        "business_types": ["농업"],
        "required_docs": ["농업경영체등록확인서", "사업계획서", "토지등기부등본"],
        "deadline": "2026-04-15",
        "org": "농림축산식품부",
    },
    {
        "id": 4,
        "name": "소상공인 경영안정자금",
        "category": "경영안정",
        "description": "매출 감소 소상공인을 위한 저금리 융자 및 보조금",
        "amount": "최대 7,000만원",
        "min_age": 19,
        "max_age": 65,
        "gender": "무관",
        "regions": ["서울", "경기", "인천", "부산", "대구", "광주", "대전", "울산", "세종", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"],
        "max_income_percentile": 100,
        "business_types": ["도소매업", "서비스업", "음식숙박업", "제조업"],
        "required_docs": ["사업자등록증", "매출증빙서류", "신분증"],
        "deadline": "2026-12-31",
        "org": "소상공인시장진흥공단",
    },
    {
        "id": 5,
        "name": "신재생에너지 설치 보조금",
        "category": "에너지",
        "description": "태양광, 지열 등 신재생에너지 설비 설치 지원",
        "amount": "설치비의 최대 50%",
        "min_age": 18,
        "max_age": 100,
        "gender": "무관",
        "regions": ["서울", "경기", "인천", "부산", "대구", "광주", "대전", "울산", "세종", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"],
        "max_income_percentile": 100,
        "business_types": ["제조업", "IT", "서비스업", "농업"],
        "required_docs": ["건축물대장", "사업자등록증", "설치계획서"],
        "deadline": "2026-09-30",
        "org": "한국에너지공단",
    },
    {
        "id": 6,
        "name": "장애인 고용장려금",
        "category": "고용",
        "description": "장애인 근로자를 고용한 사업주에게 지급하는 장려금",
        "amount": "월 최대 80만원/인",
        "min_age": 18,
        "max_age": 65,
        "gender": "무관",
        "regions": ["서울", "경기", "인천", "부산", "대구", "광주", "대전", "울산", "세종", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"],
        "max_income_percentile": 100,
        "business_types": ["제조업", "IT", "서비스업", "도소매업", "음식숙박업"],
        "required_docs": ["장애인고용확인서", "사업자등록증", "근로계약서"],
        "deadline": "2026-12-31",
        "org": "한국장애인고용공단",
    },
    {
        "id": 7,
        "name": "청년 월세 지원",
        "category": "주거",
        "description": "무주택 청년의 월세 부담 경감을 위한 지원금",
        "amount": "월 최대 20만원 (12개월)",
        "min_age": 19,
        "max_age": 34,
        "gender": "무관",
        "regions": ["서울", "경기", "인천", "부산", "대구", "광주", "대전", "울산", "세종"],
        "max_income_percentile": 60,
        "business_types": [],
        "required_docs": ["주민등록등본", "소득증명서", "임대차계약서"],
        "deadline": "2026-08-31",
        "org": "국토교통부",
    },
    {
        "id": 8,
        "name": "수출 중소기업 마케팅 지원",
        "category": "수출",
        "description": "해외 시장 진출을 위한 마케팅 비용 지원",
        "amount": "최대 1억원",
        "min_age": 18,
        "max_age": 100,
        "gender": "무관",
        "regions": ["서울", "경기", "인천", "부산", "대구", "광주", "대전", "울산", "세종", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"],
        "max_income_percentile": 100,
        "business_types": ["제조업", "IT", "서비스업"],
        "required_docs": ["사업자등록증", "수출실적증명서", "마케팅계획서"],
        "deadline": "2026-07-31",
        "org": "KOTRA",
    },
    {
        "id": 9,
        "name": "다자녀 가구 양육비 지원",
        "category": "복지",
        "description": "2자녀 이상 가구에 양육비 및 교육비 지원",
        "amount": "자녀 1인당 연 100만원",
        "min_age": 20,
        "max_age": 60,
        "gender": "무관",
        "regions": ["서울", "경기", "인천", "부산", "대구", "광주", "대전", "울산", "세종", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"],
        "max_income_percentile": 70,
        "business_types": [],
        "required_docs": ["주민등록등본", "가족관계증명서", "소득증명서"],
        "deadline": "2026-12-31",
        "org": "보건복지부",
    },
    {
        "id": 10,
        "name": "AI/디지털전환 기업 지원금",
        "category": "기술혁신",
        "description": "AI, 빅데이터 등 디지털전환 프로젝트 수행 기업 지원",
        "amount": "최대 2억원",
        "min_age": 18,
        "max_age": 100,
        "gender": "무관",
        "regions": ["서울", "경기", "인천", "부산", "대구", "광주", "대전", "울산", "세종"],
        "max_income_percentile": 100,
        "business_types": ["IT", "제조업", "서비스업"],
        "required_docs": ["사업자등록증", "기술개발계획서", "재무제표"],
        "deadline": "2026-05-15",
        "org": "과학기술정보통신부",
    },
    {
        "id": 11,
        "name": "여성 기술창업 지원금",
        "category": "창업",
        "description": "여성 기술인의 창업 및 사업화를 지원하는 보조금",
        "amount": "최대 1억원",
        "min_age": 19,
        "max_age": 55,
        "gender": "여성",
        "regions": ["서울", "경기", "인천", "부산", "대구", "광주", "대전", "울산", "세종"],
        "max_income_percentile": 100,
        "business_types": ["IT", "제조업", "서비스업"],
        "required_docs": ["사업계획서", "신분증", "기술자격증명서"],
        "deadline": "2026-07-31",
        "org": "중소벤처기업부",
    },
    {
        "id": 12,
        "name": "군 전역자 취업지원금",
        "category": "취업",
        "description": "전역 후 2년 이내 남성 대상 직업훈련 및 취업 지원",
        "amount": "최대 200만원",
        "min_age": 20,
        "max_age": 35,
        "gender": "남성",
        "regions": ["서울", "경기", "인천", "부산", "대구", "광주", "대전", "울산", "세종", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"],
        "max_income_percentile": 100,
        "business_types": [],
        "required_docs": ["전역증명서", "신분증", "소득증명서"],
        "deadline": "2026-12-31",
        "org": "국가보훈부",
    },
]

REGIONS = sorted(set(r for s in SUBSIDIES for r in s["regions"]))
CATEGORIES = sorted(set(s["category"] for s in SUBSIDIES))
BUSINESS_TYPES = sorted(set(b for s in SUBSIDIES for b in s["business_types"]))
GENDERS = ["무관", "남성", "여성"]
